### ISSUE TITLE
Few missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by adhamarif** [mesolitica/dynamic-batch-RAG-pipeline#1]
I am installing the repo for the first time and had issue with the dependencies. These dependencies were missing from the requirement.txt.

transformers
tiktoken

**Comment by huseinzol05** [comment]
why tiktoken, let me verify using Docker

**Comment by huseinzol05** [comment]
You are correct, i got error `ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run pip install tiktoken`

**Comment by huseinzol05** [comment]
fixed, able to deploy in my server
